server:
  port: 8088
spring:
  application:
    name: "DocumentsValidateGov"
  devtools:
    add-properties: false
  codec:
    max-in-memory-size: 50MB
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080,http://localhost"
snr:
  api:
    url: "https://certificados.supernotariado.gov.co/certificado/external/validation/validate.snr"
    timeout: 10000
    request-timeout-seconds: 12
ocr:
  tessdata-path: "C:/Program Files/Tesseract-OCR/tessdata"